from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

from pawbot.agent.memory_preferences import ExplicitMemoryStore
from pawbot.webui.blackbox_api import blackbox_action_factory


def _dispatcher(tmp_path: Path):
    store = ExplicitMemoryStore(tmp_path / "workspace", data_root=tmp_path / "runtime")
    agent = SimpleNamespace(context=SimpleNamespace(explicit_memory=store))
    return blackbox_action_factory(agent_getter=lambda: agent, session_manager=None)


@pytest.mark.asyncio
async def test_webui_memory_actions_round_trip(tmp_path: Path) -> None:
    dispatch = _dispatcher(tmp_path)

    saved = await dispatch(
        "memory.remember",
        {
            "scope": "global",
            "kind": "preference",
            "key": "reply_language",
            "value": "zh-CN",
        },
    )
    memory_id = saved["memory"]["memory_id"]
    listed = await dispatch("memory.list", {})
    assert listed["memories"][0]["key"] == "reply_language"

    forgotten = await dispatch("memory.forget", {"memory_id": memory_id})
    assert forgotten == {"memory_id": memory_id, "deleted": True}
    listed_after = await dispatch("memory.list", {})
    assert listed_after["memories"] == []


@pytest.mark.asyncio
async def test_webui_memory_candidate_can_be_confirmed_or_rejected(tmp_path: Path) -> None:
    dispatch = _dispatcher(tmp_path)
    agent = await dispatch(
        "memory.remember",
        {
            "scope": "workspace",
            "kind": "fact",
            "key": "primary_provider",
            "value": "deepseek",
        },
    )
    memory_id = agent["memory"]["memory_id"]
    # The HTTP surface only creates confirmed explicit records; candidate
    # promotion/rejection is exercised through the same dispatcher after a
    # candidate has been generated by the extractor path.
    promoted = await dispatch("memory.promote", {"memory_id": memory_id})
    assert promoted["memory"]["status"] == "confirmed"
